"""Shared LangGraph state for the automated testing workflow."""

from __future__ import annotations

from typing import Any, TypedDict


class TestAutomationState(TypedDict, total=False):
    """State shared by LangGraph nodes during one test automation run."""

    # LangGraph State is the shared memory of the workflow.
    # Each node reads from State and returns partial State updates.
    # Future agents will add fields such as project_info, retrieved_context,
    # test_plan, api_results, ui_results, performance_results, bug_results,
    # and reports.
    run_id: str
    repo_url: str
    target_url: str
    user_preferences: dict[str, Any]
    selected_agents: list[str]
    orchestrator_decision: dict[str, Any]
    errors: list[dict[str, Any]]
    agent_logs: list[dict[str, Any]]

    # repo_path points to the local cloned or provided repository.
    repo_path: str
    # project_info is compact repository metadata.
    project_info: dict[str, Any]
    # discovered_endpoints is a heuristic list, not final test cases.
    discovered_endpoints: list[dict[str, Any]]
    # discovered_ui_flows is a heuristic list, not final UI tests.
    discovered_ui_flows: list[dict[str, Any]]
    # indexed_documents is only candidate files for future RAG, not a vector store.
    indexed_documents: list[dict[str, Any]]

    # rag_index_path points to the local vector index folder.
    rag_index_path: str
    # rag_query is the query used for retrieval.
    rag_query: str
    # retrieved_context contains only top-k retrieved chunks, not all chunks.
    retrieved_context: list[dict[str, Any]]
    # missing_information records weak or absent repository evidence.
    missing_information: list[str]

    # test_plan is the structured plan generated by Test Planner.
    test_plan: dict[str, Any]
    # test_plan_path points to results/runs/<run_id>/test_plan.json.
    test_plan_path: str
    # test_planner_result_path points to results/runs/<run_id>/test_planner_result.json.
    test_planner_result_path: str
    # planner_model_info records deterministic/Groq/Mistral mode without secrets.
    planner_model_info: dict[str, Any]

    # api_results is the compact structured output from API Testing Agent.
    api_results: dict[str, Any]
    # api_result_path points to results/runs/<run_id>/api_result.json.
    api_result_path: str

    # ui_results is the compact structured output from UI Testing Agent.
    ui_results: dict[str, Any]
    # ui_result_path points to results/runs/<run_id>/ui_result.json.
    ui_result_path: str
    # screenshots contains screenshot metadata and paths, not binary image data.
    screenshots: list[dict[str, Any]]

    # performance_results is the compact structured output from Performance Testing Agent.
    performance_results: dict[str, Any]
    # performance_result_path points to results/runs/<run_id>/performance_result.json.
    performance_result_path: str
    # performance_artifacts contains paths to generated Locust files or CSV/JSON metrics.
    performance_artifacts: list[dict[str, Any]]

    # bug_results is the structured output from Bug Analysis Agent.
    bug_results: dict[str, Any]
    # bug_result_path points to results/runs/<run_id>/bug_result.json.
    bug_result_path: str
    # recommendations contains compact actions suggested by the Bug Agent.
    recommendations: list[dict[str, Any]]

    # final_results is the aggregate report data.
    final_results: dict[str, Any]
    # final_results_path points to results/runs/<run_id>/final_results.json.
    final_results_path: str
    # report_result is the structured output from Report Agent.
    report_result: dict[str, Any]
    # report_result_path points to results/runs/<run_id>/report_result.json.
    report_result_path: str
    # report_html_path points to reports/generated/report_<run_id>.html.
    report_html_path: str
    # dashboard_payload is a compact object for future UI rendering.
    dashboard_payload: dict[str, Any]


TestAutomationState.__test__ = False
